#!/usr/bin/env bash
#SBATCH --account=rubin:developers      # Account name
#SBATCH --job-name=auxtel_prenight_daily   # Job name
#SBATCH --output=/sdf/data/rubin/shared/scheduler/prenight/sbatch/run_prenight_sims.out # Output file (stdout)
#SBATCH --error=/sdf/data/rubin/shared/scheduler/prenight/sbatch/run_prenight_sims.err  # Error file (stderr)
#SBATCH --partition=milano              # Partition (queue) names
#SBATCH --nodes=1                       # Number of nodes
#SBATCH --ntasks=1                      # Number of tasks run in parallel
#SBATCH --cpus-per-task=1               # Number of CPUs per task
#SBATCH --mem=6G                       # Requested memory
#SBATCH --time=1:00:00                 # Wall time (hh:mm:ss)

help() {
  echo "Usage: $0 TELESCOPE_NAME"
  echo "where TELESCOPE_NAME is either \"simoniy\" or \"auxtel\"."
  echo ""
  echo "The following environment variables may be set. If they are not,"
  echo "defaults generated by querying the EFD, github, or static values"
  echo "will be used."
  echo ""
  echo "AWS_PROFILE: The aws profile to use for authentication"
  echo "WORK_DIR: The directory in which to install dependencies and run"
  echo "    the simulation."
  echo "SCHEDULER_CONFIG_SCRIPT: File name for the scheduler config script."
  echo "TS_CONFIG_OCS_REPO: git repository with the config script. Defaults"
  echo "    to https://github.com/lsst-ts/ts_config_ocs"
  echo "TS_CONFIG_OCS_VERSIONS: The version of TS_CONFIG_OCS_REPO to use,"
  echo "    either a tag or a combinaton of tag and hash, as produced"
  echo "    by \"git describe\"."
  echo "RUBIN_SCHEDULER_TAG: The version of rubin_scheduler to use."
  echo "TS_FBS_UTILS_TAG : the version of ts_fbs_utils to use."
}

if [ $# -ne 1 ]; then
  help()
  exit 1

if [ "$1" != "simonyi" ] && [ "$1" != "auxtel" ]; then
  help()
  exit 1
fi

echo "******** START of run_prenight_sims.sh **********"

date --iso=s

if [ -z $(command -v prenight_sim ) ] ; then
  # If prenight_sim is not already in our environment,
  # set up the standard prenight sim environment at the
  # USDF.

  # Source global definitions
  if [ -f /etc/bashrc ]; then
    . /etc/bashrc
  fi

  # SLAC S3DF - source all files under ~/.profile.d
  if [[ -e ~/.profile.d && -n "$(ls -A ~/.profile.d/)" ]]; then
    source <(cat $(find -L  ~/.profile.d -name '*.conf'))
  fi

  source /sdf/group/rubin/sw/w_latest/loadLSST.sh
  conda activate /sdf/data/rubin/shared/scheduler/envs/prenight
fi

set -o xtrace

export TELESCOPE=$1

if [ -z ${AWS_PROFILE+xxx} ] ; then
  export AWS_PROFILE=prenight
fi

if [ -z ${WORK_DIR+xxx} ] ; then
  WORK_DIR=$(date '+/sdf/data/rubin/shared/scheduler/prenight/work/run_prenight_sims/%Y-%m-%dT%H%M%S' --utc)
fi

echo "Working in $WORK_DIR"
mkdir ${WORK_DIR}
cd ${WORK_DIR}

# Get ts_ocs_config
if [ -z ${TS_CONFIG_OCS_REPO+xxx} ] ; then
  TS_CONFIG_OCS_REPO="https://github.com/lsst-ts/ts_config_ocs"
fi

if [ -z ${TS_CONFIG_OCS_VERSION+xxx} ] ; then
  TS_CONFIG_OCS_VERSION=$(obs_version_at_time ts_config_ocs)
fi

curl --location --output ts_config_ocs.zip ${TS_CONFIG_OCS_REPO}/archive/${TS_CONFIG_OCS_VERSION}.zip
unzip ts_config_ocs.zip
mv $(find . -maxdepth 1 -type d -name ts_config_ocs\*) ts_config_ocs

# Install required python packages
PACKAGE_DIR=$(readlink -f ${WORK_DIR}/packages)
mkdir ${PACKAGE_DIR}

if [ -z ${RUBIN_SCHEDULER_TAG+xxx} ] ; then
  # Get the scheduler version from the EFD and install it.
  RUBIN_SCHEDULER_TAG=v$(obs_version_at_time rubin_scheduler)
fi
pip install --no-deps --target=${PACKAGE_DIR} git+https://github.com/lsst/rubin_scheduler.git@${RUBIN_SCHEDULER_TAG}

if [ -z ${TS_FBS_UTILS_TAG+xxx} ] ; then
  # Cannot get ts_fbs_utils from the EFD, so just guess the highest semantic version tag in the repo.
  TS_FBS_UTILS_TAG=$(curl -s https://api.github.com/repos/lsst-ts/ts_fbs_utils/tags | jq -r '.[].name' | egrep '^v[0-9]+.[0-9]+.[0-9]+$' | sort -V | tail -1))
fi
pip install --no-deps --target=${PACKAGE_DIR} git+https://github.com/lsst-ts/ts_fbs_utils.git@${TS_FBS_UTILS_TAG}

# Get the scheduler configuration script
if [ -z ${SCHEDULER_CONFIG_SCRIPT+xxx} ] ; then
  if [ "${TELESCOPE}" -eq "simonyi" ] ; then
    # Ignore the EFD, just hardwire the simonyi scheduler config.
    SCHEDULER_CONFIG_SCRIPT="ts_config_ocs/Scheduler/feature_scheduler/maintel/fbs_config_sv_survey.py"
  else
    SCHEDULER_CONFIG_SCRIPT=$(scheduler_config_at_time ${TELESCOPE})
  fi
fi

# Get the path to prenight_sim as provided by the current environment,
# so we do not accidentally run one from the adjusted PATH below.
PRENIGHT_SIM=$(which prenight_sim)

export SIM_ARCHIVE_LOG_FILE=${WORK_DIR}/sim_archive_log.txt
export PRENIGHT_LOG_FILE=${WORK_DIR}/prenight_log.txt
export PYTHONPATH=${PACKAGE_DIR}:${PYTHONPATH}
export PATH=${PACKAGE_DIR}/bin:${PATH}
printenv > env.out
date --iso=s
time ${PRENIGHT_SIM} --scheduler ${TELESCOPE}.pickle.xz --opsim None --repo=${TS_CONFIG_OCS_REPO} --script ${SCHEDULER_CONFIG_SCRIPT} --config_version ${TS_CONFIG_OCS_VERSION} --telescope ${TELESCOPE} 2>&1 > ${WORK_DIR}/prenight_sim.out
date --iso=s
echo "******* END of run_prenight_sims.sh *********"
